CREATE DATABASE FACULDADE_RDS
USE FACULDADE_RDS

CREATE TABLE MATERIA(
CD_MATERIA INT IDENTITY NOT NULL,
NM_MATERIA VARCHAR(60) NOT NULL,
CONSTRAINT PK_MATERIA PRIMARY KEY(CD_MATERIA))

--NÃO É UMA TABELA ASSOCIATIVA
CREATE TABLE ENDEREÇO_DO_PROF(
CD_EP INT IDENTITY NOT NULL,
NR_CEP INT NULL,
NM_RUA VARCHAR (50) NOT NULL,
NR_CASA INT NOT NULL,
CD_PROFESSOR INT NOT NULL,
CONSTRAINT PK_EP PRIMARY KEY(CD_EP),
CONSTRAINT FK_ENDEREÇO_DO_PROF FOREIGN KEY (CD_PROFESSOR) REFERENCES PROFESSOR (CD_PROFESSOR))

CREATE TABLE PROFESSOR(
CD_PROFESSOR INT IDENTITY NOT NULL,
NM_PROFESSOR VARCHAR(50) NOT NULL,
VL_SALARIO NUMERIC(8,2) NOT NULL,
CD_ENDEREÇO INT NOT NULL,
NR_CPF CHAR(11) NOT NULL,
CONSTRAINT PK_PROFESSOR PRIMARY KEY (CD_PROFESSOR),
CONSTRAINT UNICO_CPF UNIQUE(NR_CPF))


CREATE TABLE CTT_PROFESSOR(
CD_PROFESSOR INT NOT NULL,
EMAIL_PESSOAL VARCHAR(70) NOT NULL,
EMAIL_INSTITUCIONAL VARCHAR(70) NOT NULL,
TEL_CELULAR NUMERIC(10,0) NOT NULL,
TEL_FIXO INT NULL,
OUTRO VARCHAR(60) NULL,
CONSTRAINT UNICO_PROFESSOR UNIQUE(CD_PROFESSOR),
CONSTRAINT FK1_PROFESSOR FOREIGN KEY (CD_PROFESSOR) REFERENCES PROFESSOR (CD_PROFESSOR))

CREATE TABLE MATERIA_PROFESSOR(
CD_MP INT IDENTITY NOT NULL,
CD_PROFESSOR INT NOT NULL,
CD_MATERIA INT NOT NULL,
CONSTRAINT PK_MP PRIMARY KEY (CD_MP),
CONSTRAINT FK2_PROFESSOR FOREIGN KEY (CD_PROFESSOR) REFERENCES PROFESSOR(CD_PROFESSOR),
CONSTRAINT FK1_MATERIA FOREIGN KEY(CD_MATERIA) REFERENCES MATERIA (CD_MATERIA))


CREATE TABLE MÊS (CD_MÊS INT IDENTITY NOT NULL, NM_MÊS VARCHAR(17) NOT NULL,
CONSTRAINT PK_MÊS PRIMARY KEY (CD_MÊS))

CREATE TABLE ANO (CD_ANO INT IDENTITY NOT NULL, NM_ANO INT NOT NULL,
CONSTRAINT PK_ANO PRIMARY KEY (CD_ANO))

-- SALÁRIO DO PROFESSOR.
CREATE TABLE REGISTRO_MENSAL_SALÁRIO
(CD_REGISTROSAL INT IDENTITY NOT NULL, 
CD_ANO INT NOT NULL,
CD_MÊS INT NOT NULL,
CD_PROFESSOR INT NOT NULL,
VL_SALÁRIO NUMERIC(18,2) NOT NULL,
CONSTRAINT PK_REGISTROSAL PRIMARY KEY(CD_REGISTROSAL),
CONSTRAINT FK_ANO FOREIGN KEY(CD_ANO) REFERENCES ANO(CD_ANO),
CONSTRAINT FK_MÊS FOREIGN KEY(CD_MÊS) REFERENCES MÊS(CD_MÊS),
CONSTRAINT FK_PROFESSOR FOREIGN KEY(CD_PROFESSOR) REFERENCES PROFESSOR(CD_PROFESSOR))

-- EM SEMESTRE
CREATE TABLE DURAÇÃO (
CD_DURAÇÃO INT IDENTITY NOT NULL,
TMP_DURAÇÃO  INT NOT NULL,
CONSTRAINT PK_DURAÇÃO PRIMARY KEY (CD_DURAÇÃO)) 

CREATE TABLE POLO 
(CD_POLO INT IDENTITY NOT NULL,
ENDEREÇO_POLO VARCHAR(80) NOT NULL,
CONSTRAINT PK_POLO PRIMARY KEY (CD_POLO))

CREATE TABLE CURSO(
CD_CURSO INT IDENTITY NOT NULL,
NM_CURSO VARCHAR(70) NOT NULL,
DURAÇÃO_CURSO INT NOT NULL,
CONSTRAINT PK_CURSO PRIMARY KEY (CD_CURSO),
CONSTRAINT FK_DURAÇÃO FOREIGN KEY (DURAÇÃO_CURSO) REFERENCES DURAÇÃO (CD_DURAÇÃO))


CREATE TABLE ALUNO 
(CD_ALUNO INT IDENTITY NOT NULL, 
NM_ALUNO VARCHAR(70) NOT NULL,
CPF_ALUNO NUMERIC(11,0) NOT NULL,
RA_ALUNO VARCHAR(10) NOT NULL,
CD_CURSO INT NOT NULL,
CD_POLO INT NOT NULL,
CONSTRAINT PK_ALUNO PRIMARY KEY (CD_ALUNO),
CONSTRAINT FK_CURSO FOREIGN KEY (CD_CURSO) REFERENCES CURSO(CD_CURSO),
CONSTRAINT FK_POLO FOREIGN KEY (CD_POLO) REFERENCES POLO(CD_POLO))

CREATE TABLE CTT_ALUNO(
CD_ALUNO INT NOT NULL,
EMAIL_PESSOAL VARCHAR(70) NOT NULL,
EMAIL_INSTITUCIONAL VARCHAR(70) NOT NULL,
TEL_CELULAR NUMERIC(10,0) NOT NULL,
TEL_FIXO INT NULL,
OUTRO VARCHAR(60) NULL,
CONSTRAINT UNICO_ALUNO UNIQUE(CD_ALUNO),
CONSTRAINT FK1_ALUNO FOREIGN KEY (CD_ALUNO) REFERENCES ALUNO (CD_ALUNO))

--METÉRIA_ALUNO (TABELA ASSOCIATIVA)
CREATE TABLE AULA
(CD_AULA INT IDENTITY NOT NULL,
CD_ALUNO INT NOT NULL,
CD_MATERIA INT NOT NULL,
CONSTRAINT PK_AULA PRIMARY KEY(CD_AULA),
CONSTRAINT FK2_ALUNO FOREIGN KEY(CD_ALUNO) REFERENCES ALUNO (CD_ALUNO),
CONSTRAINT FK2_MATERIA FOREIGN KEY(CD_MATERIA) REFERENCES MATERIA(CD_MATERIA))

CREATE TABLE ENDEREÇO_DO_ALUNO(
CD_EA INT IDENTITY NOT NULL,
NR_CEP INT NULL,
NM_RUA VARCHAR (50) NOT NULL,
NR_CASA INT NOT NULL,
CD_ALUNO INT NOT NULL,
CONSTRAINT PK_EA PRIMARY KEY(CD_EA),
CONSTRAINT FK_ENDEREÇO_DO_ALUNO FOREIGN KEY (CD_ALUNO) REFERENCES ALUNO (CD_ALUNO))


  
ALTER TABLE PROFESSOR ADD DT_ADMISSÃO DATE

CREATE TABLE PROFESSOR_MATÉRIA (CD_PM INT IDENTITY NOT NULL, CD_PROFESSOR INT NOT NULL, CD_MATÉRIA INT NOT NULL,
CONSTRAINT PK_PM PRIMARY KEY (CD_PM),
CONSTRAINT FK_PROFESSOR FOREIGN KEY (CD_PROFESSOR) REFERENCES PROFESSOR (CD_PROFESSOR),
CONSTRAINT FK_MATÉRIA FOREIGN KEY (CD_MATÉRIA) REFERENCES MATÉRIA (CD_PROFESSOR))


ALTER TABLE REGISTRO_MENSAL_SALÁRIO ADD PORCENTAGEM_ALTERAÇÃO VARCHAR(10)
